using Microsoft.AspNetCore.Identity.MongoDB;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using NUlid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lexiconner.IdentityServer4.Entities
{
    public class ApplicationRole : IdentityRole
    {
        
        public ApplicationRole()
        {
            // don't use custom id because BsonRepresentation(BsonType.ObjectId) applied in base class
            // and it must be 24 digit hex string that is generated by MongoDb
            // Id = Ulid.NewUlid().ToString();
        }
    }
}
