"use strict";

const storeTypes = {
  LOADING_SET: "LOADING_SET",

  AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SET: "AUTH_LOGIN_SET",
  AUTH_USER_SET: "AUTH_USER_SET",
  AUTH_USER_RESET: "AUTH_USER_RESET",
};

export { storeTypes };
