"use strict";

const storeTypes = {
  LOADING_SET: "LOADING_SET",

  AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SET: "AUTH_LOGIN_SET",
  AUTH_USER_SET: "AUTH_USER_SET",
  AUTH_USER_RESET: "AUTH_USER_RESET",

  PROFILE_LOAD: "PROFILE_LOAD",
  PROFILE_SET: "PROFILE_SET",
  PROFILE_SELECT_LEARNING_LANGUAGE: "PROFILE_SELECT_LEARNING_LANGUAGE",

  LANGUAGES_LOAD: "LANGUAGES_LOAD",
  LANGUAGES_SET: "LANGUAGES_SET",

  WORD_LAST_ADDED_LOAD: "WORD_LAST_ADDED_LOAD",
  WORD_LAST_ADDED_SET: "WORD_LAST_ADDED_SET",
  WORD_MEANINGS_LOAD: "WORD_MEANINGS_LOAD",
  WORD_MEANINGS_SET: "WORD_MEANINGS_SET",
  WORD_CREATE: "WORD_CREATE",
  WORD_CREATE_SET: "WORD_CREATE_SET",
};

export { storeTypes };
