using Microsoft.AspNetCore.Identity.MongoDB;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;
using NUlid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lexiconner.Domain.Entitites
{
    public class ApplicationUserEntity : IdentityUser
    {
        public ApplicationUserEntity()
        {
            // don't use custom id because BsonRepresentation(BsonType.ObjectId) applied in base class
            // and it must be 24 digit hex string that is generated by MongoDb
            // Id = Ulid.NewUlid().ToString();
        }

        public string Name { get; set; }

        /// <summary>
        /// true - create imported data for user
        /// </summary>
        public bool IsImportInitialData { get; set; }
    }
}
