'use strict';

const storeTypes = {
    'LOADING_SET': 'LOADING_SET',

    'ENUMS_LOAD': 'ENUMS_LOAD',
    'ENUMS_SET': 'ENUMS_SET',

    'CONFIG_LOAD': 'CONFIG_LOAD',
    'CONFIG_SET': 'CONFIG_SET',

    'TERMS_OF_USE_LOAD': 'TERMS_OF_USE_LOAD',
    'TERMS_OF_USE_SET': 'TERMS_OF_USE_SET',
    'COUNTRIES_LOAD': 'COUNTRIES_LOAD',
    'COUNTRIES_SET': 'COUNTRIES_SET',
    'LANGUAGES_LOAD': 'LANGUAGES_LOAD',
    'LANGUAGES_SET': 'LANGUAGES_SET',
    'TIMEZONES_LOAD': 'TIMEZONES_LOAD',
    'TIMEZONES_SET': 'TIMEZONES_SET',

    'AUTH_USER_SET': 'AUTH_USER_SET',
    'AUTH_USER_RESET': 'AUTH_USER_RESET',

    'USER_INFO_LOAD': 'USER_INFO_LOAD',
    'USER_INFO_SET': 'USER_INFO_SET',
    'USER_INFO_UPDATE': 'USER_INFO_UPDATE',
    'USER_INFO_NOTIFICATIONS_UPDATE': 'USER_INFO_NOTIFICATIONS_UPDATE',
    'USER_INFO_TIMEZONE_SET': 'USER_INFO_TIMEZONE_SET',
    'USER_INFO_CURRENT_COMPANY_SET': 'USER_INFO_CURRENT_COMPANY_SET',

    'STUDY_ITEMS_LOAD': 'STUDY_ITEMS_LOAD',
    'STUDY_ITEMS_SET': 'STUDY_ITEMS_SET',
    'STUDY_ITEM_LOAD': 'STUDY_ITEM_LOAD',
    'STUDY_ITEM_CREATE': 'STUDY_ITEM_CREATE',
    'STUDY_ITEM_UPDATE': 'STUDY_ITEM_UPDATE',
    'STUDY_ITEM_DELETE': 'STUDY_ITEM_DELETE',

    'NAV_VISIBILITY_SET': 'NAV_VISIBILITY_SET',

    'ERROR_PAGE_DATA_SET': 'ERROR_PAGE_DATA_SET',
    'ERROR_PAGE_DATA_RESET': 'ERROR_PAGE_DATA_RESET',
}

export {
    storeTypes,
}
